### ISSUE TITLE
Implement RNN models in the pipeline

### ISSUE THREAD

**Issue by arunasank** [forrestdavis/PublicModelsAPI#1]
Add RNN models to the pipeline.

**Comment by forrestdavis** [comment]
They should work, but one has to be careful with the versioning. Did you have a use case in mind?

**Comment by arunasank** [comment]
I don't see it in the models folder -- but I do see them in another folder. Will spend some time understanding the pipeline. This is just to replicate the Gulordova work. :)

**Comment by forrestdavis** [comment]
So I think I have this working. I've added an example config file (lstm_config.yaml) which shows how to run the best gulordava English model. I dumped the state dict for gulordava's model in older pytorch and loaded it into a new model which should work. One would want to dig into this more if this was to be published, but it should be sufficient to get a decent replication. For good measure, I've "updated" the best English, Hebrew, Italian, and Russian models to run with newer pytorch (which is need for this pipeline). You can find them all (and their vocab files) [here](https://drive.google.com/file/d/11V-W9fymHc_2293uWtImPY1XcoeMEEYs/view?usp=sharing). 

Running 

```python
python main.py lstm_config.yaml
```

Will trigger the interact shell with the english lstm model. To get it running with some stimuli file, simply copy that info from the readme and point to the right file (as we discussed). It should work with the other models, but I haven't tested them. As always, let me know if you have any questions.
